---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: proofline-prod

resources:
  - ../../base

commonLabels:
  app.kubernetes.io/instance: prod

patches:
  - path: production-hardening.yaml
    target:
      kind: Deployment
      name: proofline
  - path: hpa.yaml
    target:
      kind: HorizontalPodAutoscaler
      name: proofline
